#!/usr/bin/env node
// npm run gen:api (SPEC §13.3): write src/api/schema.gen.ts from the server's OpenAPI document.
//
// The document comes from `python -m sparc.studio --dump-openapi <tmp>` (no server needed),
// run from the repository root so the checkout's `sparc` package is used. Options:
//   --input <openapi.json>   use an existing document instead of running Python
//   --out <file>             output path (default src/api/schema.gen.ts)
//   --python <exe>           Python interpreter (default $PYTHON, else python3, else python)
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(here, "..");
const repoRoot = resolve(webRoot, "..");

function arg(name) {
  const i = process.argv.indexOf(name);
  return i > 0 ? process.argv[i + 1] : undefined;
}

function pickPython() {
  const explicit = arg("--python") ?? process.env.PYTHON;
  if (explicit) return explicit;
  for (const exe of ["python3", "python"]) {
    try {
      execFileSync(exe, ["--version"], { stdio: "ignore" });
      return exe;
    } catch {
      /* try the next one */
    }
  }
  throw new Error("No Python interpreter found; pass --python or set PYTHON");
}

async function main() {
  const out = resolve(webRoot, arg("--out") ?? "src/api/schema.gen.ts");
  let input = arg("--input");
  let tmp = null;
  if (!input) {
    tmp = mkdtempSync(join(tmpdir(), "sparc-openapi-"));
    input = join(tmp, "openapi.json");
    const python = pickPython();
    console.log(`gen:api: ${python} -m sparc.studio --dump-openapi ${input}`);
    execFileSync(python, ["-m", "sparc.studio", "--dump-openapi", input], { cwd: repoRoot, stdio: "inherit" });
  }
  try {
    const doc = JSON.parse(readFileSync(resolve(input), "utf8"));
    const ast = await openapiTS(doc, { alphabetize: true });
    const header =
      "// Generated by `npm run gen:api` from the Studio OpenAPI document. Do not edit.\n" +
      `// API: ${doc.info?.title ?? "SPARC Studio"} ${doc.info?.version ?? ""}\n\n`;
    writeFileSync(out, header + astToString(ast));
    console.log(`gen:api: wrote ${out}`);
  } finally {
    if (tmp) rmSync(tmp, { recursive: true, force: true });
  }
}

main().catch((e) => {
  console.error(`gen:api failed: ${e?.message ?? e}`);
  process.exit(1);
});
