/**
 * In-memory store for the sidecar session token.
 *
 * The token is generated by Tauri at launch and passed to the sidecar via
 * `SPARC_SERVER_TOKEN`. The webview retrieves it once via the
 * `get_sidecar_token` Tauri command and holds it here in memory only —
 * never in localStorage, sessionStorage, or any disk storage.
 *
 * Every sidecar HTTP request includes it as `X-SPARC-Token` so the FastAPI
 * middleware can reject calls from any other process on the machine.
 */

let _token = "";

export function setToken(t: string): void {
  _token = t;
}

export function getToken(): string {
  return _token;
}
